### ISSUE TITLE
-of を指定しなかった場合にassert

### ISSUE THREAD

**Issue by setminami** [setminami/TableReconstructor#47]
```
$ jsonica/jsonica.py g -i ./Samples/cheatsheet.xlsx -hr 2
Analyzing... /Users/set/Desktop/Github/JSON_XLSX_Manager/Samples/cheatsheet.xlsx
Traceback (most recent call last):
  File "jsonica/jsonica.py", line 86, in <module>
    ins.test()
  File "jsonica/jsonica.py", line 45, in test
    subcommand.__run__(args=args)
  File "/Users/set/Desktop/Github/JSON_XLSX_Manager/jsonica/sub_command_core/generate.py", line 39, in __run__
    j = x.generateJSON(sheet_name=args.root_sheet)
  File "/Users/set/Desktop/Github/JSON_XLSX_Manager/jsonica/xlsx.py", line 47, in generateJSON
    self.__outputCSV(self.format_output, root_sheet, self.char_encode)
  File "/Users/set/Desktop/Github/JSON_XLSX_Manager/jsonica/xlsx.py", line 109, in __outputCSV
    assert self.format in output_formats
AssertionError
```

**Comment by setminami** [comment]
`AnalyzeXSeparatedOutPath(argparse.Action)`挙動に起因
