### ISSUE TITLE
githubpagesとsphinx構築依存関係

### ISSUE THREAD

**Issue by setminami** [setminami/TableReconstructor#58]

**Comment by setminami** [comment]
#59 のようにprで.nojekyllがdocs/にない場合は、githubpagesはmdから正常に構築される
直接masterへpushすると、ghpagesの構築に失敗するケースが少なくとも存在する

なお、#59では.nojekyll無し ghpages構築成功、sphinx失敗

pr時内部で何かキックしている？

**Comment by setminami** [comment]
#60 travis通過直後に、404へ切り替わった？
merge直後に見ると、sphinx themeも適応されていたがしばらくするとJsonic/が404にされてしまう。

travis ログ確認。

**Comment by setminami** [comment]
[24.1.log](https://github.com/setminami/Jsonica/files/1632807/24.1.log)
特に引っかかる箇所無し。

ローカルでdeployしたものをpushではなくtravisからコミットさせることがghpages構築の必要条件？
https://docs.travis-ci.com/user/deployment/pages/

この場合、別branch方式の方が管理しやすいかもしれない

**Comment by setminami** [comment]
https://jekyllrb.com/docs/configuration/

**Comment by setminami** [comment]
3.6 f-strのせいでschema_helper以外moduleに列挙されない？
∵ schema_helperはf-strを使っていない

https://readthedocs.org/projects/jsonica/builds/6574387/

python /home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/bin/sphinx-build -T -b readthedocssinglehtmllocalmedia -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

```
/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/docs/api_doc/jsonica.rst:4: WARNING: autodoc: failed to import module 'jsonica'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/jsonica.py", line 33
    f'"{name}" collision were detected in {self.sub_commands.keys()}'
                                                                    ^
SyntaxError: invalid syntax
/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/docs/api_doc/settings.rst:4: WARNING: autodoc: failed to import module 'settings'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/settings.py", line 48
    schema = f'{c[SCHEMA]}'.lower()
                          ^
SyntaxError: invalid syntax
/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/docs/api_doc/sub_command_core.rst:16: WARNING: autodoc: failed to import module 'sub_command_core'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/sub_command_core/__init__.py", line 2, in <module>
    from .sub_command import SubCommands
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/sub_command_core/sub_command.py", line 90
    action='version', version=f'{PROGNAME} {self.command_name} v{self.VERSION}')
                                                                              ^
SyntaxError: invalid syntax
/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/docs/api_doc/sub_command_core.generate.rst:4: WARNING: autodoc: failed to import module 'sub_command_core.generate'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/sub_command_core/__init__.py", line 2, in <module>
    from .sub_command import SubCommands
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/sub_command_core/sub_command.py", line 90
    action='version', version=f'{PROGNAME} {self.command_name} v{self.VERSION}')
                                                                              ^
SyntaxError: invalid syntax
/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/docs/api_doc/sub_command_core.initialize.rst:4: WARNING: autodoc: failed to import module 'sub_command_core.initialize'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/sub_command_core/__init__.py", line 2, in <module>
    from .sub_command import SubCommands
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/sub_command_core/sub_command.py", line 90
    action='version', version=f'{PROGNAME} {self.command_name} v{self.VERSION}')
                                                                              ^
SyntaxError: invalid syntax
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... /home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/docs/api_doc/sub_command_core.sub_command.rst:4: WARNING: autodoc: failed to import module 'sub_command_core.sub_command'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/sub_command_core/__init__.py", line 2, in <module>
    from .sub_command import SubCommands
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/sub_command_core/sub_command.py", line 90
    action='version', version=f'{PROGNAME} {self.command_name} v{self.VERSION}')
                                                                              ^
SyntaxError: invalid syntax
/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/docs/api_doc/util.rst:4: WARNING: autodoc: failed to import module 'util'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/util.py", line 44
    local = f'"{key}": {value}'
                              ^
SyntaxError: invalid syntax
/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/docs/api_doc/xlsx.rst:4: WARNING: autodoc: failed to import module 'xlsx'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/envs/doc-struct_docs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jsonica/checkouts/doc-struct_docs/jsonica/xlsx.py", line 36
    self.__print(f'in process {sheet_name}')
```

**Comment by setminami** [comment]
この時点readthedocsが3.5までしか対応していないため、readthedocsでの表示がしたい場合はf-strは使えない。

少し考える・・・
